/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MpesaTestRouteImport } from './routes/mpesa-test'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesktopIndexRouteImport } from './routes/desktop.index'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as DesktopOperationsRouteImport } from './routes/desktop.operations'
import { Route as DesktopFinanceRouteImport } from './routes/desktop.finance'
import { Route as DesktopEmployeesRouteImport } from './routes/desktop.employees'
import { Route as ApiMpesaStkPushRouteImport } from './routes/api/mpesa-stk-push'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as ApiPublicSendSmsRouteImport } from './routes/api/public/send-sms'
import { Route as ApiPublicPaymentEvidenceRouteImport } from './routes/api/public/payment-evidence'
import { Route as ApiPublicMpesaWebhookRouteImport } from './routes/api/public/mpesa-webhook'
import { Route as ApiPublicGeminiOcrRouteImport } from './routes/api/public/gemini-ocr'
import { Route as ApiAdminEmployeesRouteImport } from './routes/api/admin/employees'
import { Route as ApiAdminDeleteUserRouteImport } from './routes/api/admin/delete-user'
import { Route as ApiPublicAdminEmployeesRouteImport } from './routes/api/public/admin/employees'
import { Route as ApiPublicAdminDeleteUserRouteImport } from './routes/api/public/admin/delete-user'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MpesaTestRoute = MpesaTestRouteImport.update({
  id: '/mpesa-test',
  path: '/mpesa-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopIndexRoute = DesktopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesktopRoute,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PackagesRoute,
} as any)
const DesktopOperationsRoute = DesktopOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => DesktopRoute,
} as any)
const DesktopFinanceRoute = DesktopFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DesktopRoute,
} as any)
const DesktopEmployeesRoute = DesktopEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DesktopRoute,
} as any)
const ApiMpesaStkPushRoute = ApiMpesaStkPushRouteImport.update({
  id: '/api/mpesa-stk-push',
  path: '/api/mpesa-stk-push',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendSmsRoute = ApiPublicSendSmsRouteImport.update({
  id: '/api/public/send-sms',
  path: '/api/public/send-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentEvidenceRoute =
  ApiPublicPaymentEvidenceRouteImport.update({
    id: '/api/public/payment-evidence',
    path: '/api/public/payment-evidence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaWebhookRoute = ApiPublicMpesaWebhookRouteImport.update({
  id: '/api/public/mpesa-webhook',
  path: '/api/public/mpesa-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeminiOcrRoute = ApiPublicGeminiOcrRouteImport.update({
  id: '/api/public/gemini-ocr',
  path: '/api/public/gemini-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmployeesRoute = ApiAdminEmployeesRouteImport.update({
  id: '/api/admin/employees',
  path: '/api/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteUserRoute = ApiAdminDeleteUserRouteImport.update({
  id: '/api/admin/delete-user',
  path: '/api/admin/delete-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminEmployeesRoute = ApiPublicAdminEmployeesRouteImport.update({
  id: '/api/public/admin/employees',
  path: '/api/public/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDeleteUserRoute =
  ApiPublicAdminDeleteUserRouteImport.update({
    id: '/api/public/admin/delete-user',
    path: '/api/public/admin/delete-user',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/desktop': typeof DesktopRouteWithChildren
  '/mpesa-test': typeof MpesaTestRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/scan': typeof ScanRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/api/mpesa-stk-push': typeof ApiMpesaStkPushRoute
  '/desktop/employees': typeof DesktopEmployeesRoute
  '/desktop/finance': typeof DesktopFinanceRoute
  '/desktop/operations': typeof DesktopOperationsRoute
  '/packages/$id': typeof PackagesIdRoute
  '/desktop/': typeof DesktopIndexRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/admin/employees': typeof ApiAdminEmployeesRoute
  '/api/public/gemini-ocr': typeof ApiPublicGeminiOcrRoute
  '/api/public/mpesa-webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/payment-evidence': typeof ApiPublicPaymentEvidenceRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
  '/api/public/admin/delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/admin/employees': typeof ApiPublicAdminEmployeesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/mpesa-test': typeof MpesaTestRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/scan': typeof ScanRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/api/mpesa-stk-push': typeof ApiMpesaStkPushRoute
  '/desktop/employees': typeof DesktopEmployeesRoute
  '/desktop/finance': typeof DesktopFinanceRoute
  '/desktop/operations': typeof DesktopOperationsRoute
  '/packages/$id': typeof PackagesIdRoute
  '/desktop': typeof DesktopIndexRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/admin/employees': typeof ApiAdminEmployeesRoute
  '/api/public/gemini-ocr': typeof ApiPublicGeminiOcrRoute
  '/api/public/mpesa-webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/payment-evidence': typeof ApiPublicPaymentEvidenceRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
  '/api/public/admin/delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/admin/employees': typeof ApiPublicAdminEmployeesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/desktop': typeof DesktopRouteWithChildren
  '/mpesa-test': typeof MpesaTestRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/scan': typeof ScanRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/api/mpesa-stk-push': typeof ApiMpesaStkPushRoute
  '/desktop/employees': typeof DesktopEmployeesRoute
  '/desktop/finance': typeof DesktopFinanceRoute
  '/desktop/operations': typeof DesktopOperationsRoute
  '/packages/$id': typeof PackagesIdRoute
  '/desktop/': typeof DesktopIndexRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/admin/employees': typeof ApiAdminEmployeesRoute
  '/api/public/gemini-ocr': typeof ApiPublicGeminiOcrRoute
  '/api/public/mpesa-webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/payment-evidence': typeof ApiPublicPaymentEvidenceRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
  '/api/public/admin/delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/admin/employees': typeof ApiPublicAdminEmployeesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/desktop'
    | '/mpesa-test'
    | '/notifications'
    | '/packages'
    | '/scan'
    | '/admin/employees'
    | '/api/mpesa-stk-push'
    | '/desktop/employees'
    | '/desktop/finance'
    | '/desktop/operations'
    | '/packages/$id'
    | '/desktop/'
    | '/api/admin/delete-user'
    | '/api/admin/employees'
    | '/api/public/gemini-ocr'
    | '/api/public/mpesa-webhook'
    | '/api/public/payment-evidence'
    | '/api/public/send-sms'
    | '/api/public/admin/delete-user'
    | '/api/public/admin/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/mpesa-test'
    | '/notifications'
    | '/packages'
    | '/scan'
    | '/admin/employees'
    | '/api/mpesa-stk-push'
    | '/desktop/employees'
    | '/desktop/finance'
    | '/desktop/operations'
    | '/packages/$id'
    | '/desktop'
    | '/api/admin/delete-user'
    | '/api/admin/employees'
    | '/api/public/gemini-ocr'
    | '/api/public/mpesa-webhook'
    | '/api/public/payment-evidence'
    | '/api/public/send-sms'
    | '/api/public/admin/delete-user'
    | '/api/public/admin/employees'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/desktop'
    | '/mpesa-test'
    | '/notifications'
    | '/packages'
    | '/scan'
    | '/admin/employees'
    | '/api/mpesa-stk-push'
    | '/desktop/employees'
    | '/desktop/finance'
    | '/desktop/operations'
    | '/packages/$id'
    | '/desktop/'
    | '/api/admin/delete-user'
    | '/api/admin/employees'
    | '/api/public/gemini-ocr'
    | '/api/public/mpesa-webhook'
    | '/api/public/payment-evidence'
    | '/api/public/send-sms'
    | '/api/public/admin/delete-user'
    | '/api/public/admin/employees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CommissionsRoute: typeof CommissionsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DesktopRoute: typeof DesktopRouteWithChildren
  MpesaTestRoute: typeof MpesaTestRoute
  NotificationsRoute: typeof NotificationsRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  ScanRoute: typeof ScanRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  ApiMpesaStkPushRoute: typeof ApiMpesaStkPushRoute
  ApiAdminDeleteUserRoute: typeof ApiAdminDeleteUserRoute
  ApiAdminEmployeesRoute: typeof ApiAdminEmployeesRoute
  ApiPublicGeminiOcrRoute: typeof ApiPublicGeminiOcrRoute
  ApiPublicMpesaWebhookRoute: typeof ApiPublicMpesaWebhookRoute
  ApiPublicPaymentEvidenceRoute: typeof ApiPublicPaymentEvidenceRoute
  ApiPublicSendSmsRoute: typeof ApiPublicSendSmsRoute
  ApiPublicAdminDeleteUserRoute: typeof ApiPublicAdminDeleteUserRoute
  ApiPublicAdminEmployeesRoute: typeof ApiPublicAdminEmployeesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpesa-test': {
      id: '/mpesa-test'
      path: '/mpesa-test'
      fullPath: '/mpesa-test'
      preLoaderRoute: typeof MpesaTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/': {
      id: '/desktop/'
      path: '/'
      fullPath: '/desktop/'
      preLoaderRoute: typeof DesktopIndexRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/desktop/operations': {
      id: '/desktop/operations'
      path: '/operations'
      fullPath: '/desktop/operations'
      preLoaderRoute: typeof DesktopOperationsRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/desktop/finance': {
      id: '/desktop/finance'
      path: '/finance'
      fullPath: '/desktop/finance'
      preLoaderRoute: typeof DesktopFinanceRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/desktop/employees': {
      id: '/desktop/employees'
      path: '/employees'
      fullPath: '/desktop/employees'
      preLoaderRoute: typeof DesktopEmployeesRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/api/mpesa-stk-push': {
      id: '/api/mpesa-stk-push'
      path: '/api/mpesa-stk-push'
      fullPath: '/api/mpesa-stk-push'
      preLoaderRoute: typeof ApiMpesaStkPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-sms': {
      id: '/api/public/send-sms'
      path: '/api/public/send-sms'
      fullPath: '/api/public/send-sms'
      preLoaderRoute: typeof ApiPublicSendSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-evidence': {
      id: '/api/public/payment-evidence'
      path: '/api/public/payment-evidence'
      fullPath: '/api/public/payment-evidence'
      preLoaderRoute: typeof ApiPublicPaymentEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa-webhook': {
      id: '/api/public/mpesa-webhook'
      path: '/api/public/mpesa-webhook'
      fullPath: '/api/public/mpesa-webhook'
      preLoaderRoute: typeof ApiPublicMpesaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gemini-ocr': {
      id: '/api/public/gemini-ocr'
      path: '/api/public/gemini-ocr'
      fullPath: '/api/public/gemini-ocr'
      preLoaderRoute: typeof ApiPublicGeminiOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/employees': {
      id: '/api/admin/employees'
      path: '/api/admin/employees'
      fullPath: '/api/admin/employees'
      preLoaderRoute: typeof ApiAdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-user': {
      id: '/api/admin/delete-user'
      path: '/api/admin/delete-user'
      fullPath: '/api/admin/delete-user'
      preLoaderRoute: typeof ApiAdminDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/employees': {
      id: '/api/public/admin/employees'
      path: '/api/public/admin/employees'
      fullPath: '/api/public/admin/employees'
      preLoaderRoute: typeof ApiPublicAdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/delete-user': {
      id: '/api/public/admin/delete-user'
      path: '/api/public/admin/delete-user'
      fullPath: '/api/public/admin/delete-user'
      preLoaderRoute: typeof ApiPublicAdminDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DesktopRouteChildren {
  DesktopEmployeesRoute: typeof DesktopEmployeesRoute
  DesktopFinanceRoute: typeof DesktopFinanceRoute
  DesktopOperationsRoute: typeof DesktopOperationsRoute
  DesktopIndexRoute: typeof DesktopIndexRoute
}

const DesktopRouteChildren: DesktopRouteChildren = {
  DesktopEmployeesRoute: DesktopEmployeesRoute,
  DesktopFinanceRoute: DesktopFinanceRoute,
  DesktopOperationsRoute: DesktopOperationsRoute,
  DesktopIndexRoute: DesktopIndexRoute,
}

const DesktopRouteWithChildren =
  DesktopRoute._addFileChildren(DesktopRouteChildren)

interface PackagesRouteChildren {
  PackagesIdRoute: typeof PackagesIdRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesIdRoute: PackagesIdRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CommissionsRoute: CommissionsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DesktopRoute: DesktopRouteWithChildren,
  MpesaTestRoute: MpesaTestRoute,
  NotificationsRoute: NotificationsRoute,
  PackagesRoute: PackagesRouteWithChildren,
  ScanRoute: ScanRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  ApiMpesaStkPushRoute: ApiMpesaStkPushRoute,
  ApiAdminDeleteUserRoute: ApiAdminDeleteUserRoute,
  ApiAdminEmployeesRoute: ApiAdminEmployeesRoute,
  ApiPublicGeminiOcrRoute: ApiPublicGeminiOcrRoute,
  ApiPublicMpesaWebhookRoute: ApiPublicMpesaWebhookRoute,
  ApiPublicPaymentEvidenceRoute: ApiPublicPaymentEvidenceRoute,
  ApiPublicSendSmsRoute: ApiPublicSendSmsRoute,
  ApiPublicAdminDeleteUserRoute: ApiPublicAdminDeleteUserRoute,
  ApiPublicAdminEmployeesRoute: ApiPublicAdminEmployeesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
