/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MpesaTestRouteImport } from './routes/mpesa-test'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as ApiMpesaStkPushRouteImport } from './routes/api/mpesa-stk-push'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as ApiPublicSendSmsRouteImport } from './routes/api/public/send-sms'
import { Route as ApiPublicMpesaWebhookRouteImport } from './routes/api/public/mpesa-webhook'
import { Route as ApiPublicGeminiOcrRouteImport } from './routes/api/public/gemini-ocr'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MpesaTestRoute = MpesaTestRouteImport.update({
  id: '/mpesa-test',
  path: '/mpesa-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PackagesRoute,
} as any)
const ApiMpesaStkPushRoute = ApiMpesaStkPushRouteImport.update({
  id: '/api/mpesa-stk-push',
  path: '/api/mpesa-stk-push',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendSmsRoute = ApiPublicSendSmsRouteImport.update({
  id: '/api/public/send-sms',
  path: '/api/public/send-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaWebhookRoute = ApiPublicMpesaWebhookRouteImport.update({
  id: '/api/public/mpesa-webhook',
  path: '/api/public/mpesa-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeminiOcrRoute = ApiPublicGeminiOcrRouteImport.update({
  id: '/api/public/gemini-ocr',
  path: '/api/public/gemini-ocr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/mpesa-test': typeof MpesaTestRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/scan': typeof ScanRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/api/mpesa-stk-push': typeof ApiMpesaStkPushRoute
  '/packages/$id': typeof PackagesIdRoute
  '/api/public/gemini-ocr': typeof ApiPublicGeminiOcrRoute
  '/api/public/mpesa-webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/mpesa-test': typeof MpesaTestRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/scan': typeof ScanRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/api/mpesa-stk-push': typeof ApiMpesaStkPushRoute
  '/packages/$id': typeof PackagesIdRoute
  '/api/public/gemini-ocr': typeof ApiPublicGeminiOcrRoute
  '/api/public/mpesa-webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/mpesa-test': typeof MpesaTestRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/scan': typeof ScanRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/api/mpesa-stk-push': typeof ApiMpesaStkPushRoute
  '/packages/$id': typeof PackagesIdRoute
  '/api/public/gemini-ocr': typeof ApiPublicGeminiOcrRoute
  '/api/public/mpesa-webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/mpesa-test'
    | '/notifications'
    | '/packages'
    | '/scan'
    | '/admin/employees'
    | '/api/mpesa-stk-push'
    | '/packages/$id'
    | '/api/public/gemini-ocr'
    | '/api/public/mpesa-webhook'
    | '/api/public/send-sms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/mpesa-test'
    | '/notifications'
    | '/packages'
    | '/scan'
    | '/admin/employees'
    | '/api/mpesa-stk-push'
    | '/packages/$id'
    | '/api/public/gemini-ocr'
    | '/api/public/mpesa-webhook'
    | '/api/public/send-sms'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/mpesa-test'
    | '/notifications'
    | '/packages'
    | '/scan'
    | '/admin/employees'
    | '/api/mpesa-stk-push'
    | '/packages/$id'
    | '/api/public/gemini-ocr'
    | '/api/public/mpesa-webhook'
    | '/api/public/send-sms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CommissionsRoute: typeof CommissionsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  MpesaTestRoute: typeof MpesaTestRoute
  NotificationsRoute: typeof NotificationsRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  ScanRoute: typeof ScanRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  ApiMpesaStkPushRoute: typeof ApiMpesaStkPushRoute
  ApiPublicGeminiOcrRoute: typeof ApiPublicGeminiOcrRoute
  ApiPublicMpesaWebhookRoute: typeof ApiPublicMpesaWebhookRoute
  ApiPublicSendSmsRoute: typeof ApiPublicSendSmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpesa-test': {
      id: '/mpesa-test'
      path: '/mpesa-test'
      fullPath: '/mpesa-test'
      preLoaderRoute: typeof MpesaTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/api/mpesa-stk-push': {
      id: '/api/mpesa-stk-push'
      path: '/api/mpesa-stk-push'
      fullPath: '/api/mpesa-stk-push'
      preLoaderRoute: typeof ApiMpesaStkPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-sms': {
      id: '/api/public/send-sms'
      path: '/api/public/send-sms'
      fullPath: '/api/public/send-sms'
      preLoaderRoute: typeof ApiPublicSendSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa-webhook': {
      id: '/api/public/mpesa-webhook'
      path: '/api/public/mpesa-webhook'
      fullPath: '/api/public/mpesa-webhook'
      preLoaderRoute: typeof ApiPublicMpesaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gemini-ocr': {
      id: '/api/public/gemini-ocr'
      path: '/api/public/gemini-ocr'
      fullPath: '/api/public/gemini-ocr'
      preLoaderRoute: typeof ApiPublicGeminiOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PackagesRouteChildren {
  PackagesIdRoute: typeof PackagesIdRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesIdRoute: PackagesIdRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CommissionsRoute: CommissionsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  MpesaTestRoute: MpesaTestRoute,
  NotificationsRoute: NotificationsRoute,
  PackagesRoute: PackagesRouteWithChildren,
  ScanRoute: ScanRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  ApiMpesaStkPushRoute: ApiMpesaStkPushRoute,
  ApiPublicGeminiOcrRoute: ApiPublicGeminiOcrRoute,
  ApiPublicMpesaWebhookRoute: ApiPublicMpesaWebhookRoute,
  ApiPublicSendSmsRoute: ApiPublicSendSmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
